### ISSUE TITLE
Problem with global theming in Edge

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-docfx-template#135] opened 2019-10-29 14:14 UTC
When dark theme is selected at a topic and a navigation to other ropic is triggered, the dark theme is not applied to the iframes of the newly navigated opic

**Comment by dkamburov** [comment] 2020-02-06 09:12
Here's the pull request for the theming widget https://github.com/IgniteUI/igniteui-angular-samples/pull/1740
I believe the root cause is similar.

**Comment by ChronosSF** [comment] 2020-02-06 15:50
Assigning this to myself. We fixed the Theming Widget issue in Edge and there is a PR for IE so after 9.0 is released this will be obsolete.

**Comment by MayaKirova** [comment] 2020-02-13 09:39
Resolved with IgniteUI/igniteui-angular-samples#1740

**Closed by MayaKirova** 2020-02-13 09:39 UTC
Labels: bug, status: resolved
